### ISSUE TITLE
Unable to use sendoff in Python 3.8

### ISSUE THREAD

**Issue by coleb** [pechersky/sendoff#1]
from sendoff.sdblock import SDBlock
  File "/Users/bcole/anaconda3/envs/OE2020.2/lib/python3.8/site-packages/sendoff/sdblock.py", line 11, in <module>
    Pathy = Union[str, bytes, os.PathLike[Any]]
TypeError: 'ABCMeta' object is not subscriptable

**Comment by pechersky** [comment]
With 20fc374cde781b9330d518784287a3d8655758a0 and #2, this is solved and now tested by CI.
