### ISSUE TITLE
write method should append newline character if not present

### ISSUE THREAD

**Issue by coleb** [pechersky/sendoff#5]
Both "from_block_lines" and "from_lines" methods are documented as allowing lines without the newline character present, "optionally have whitespace that is stripped", this is how lines are generated by the Python built-in splitlines. 

However, the "write" method does not detect this case and properly append a newline character, this causes write to output a malformed SDF file.

**Comment by pechersky** [comment]
Can you share the code causing issues? I can add it as a test. In general, there are helper methods that use `open(filename).readlines()` as opposed to `splitlines`:
https://github.com/pechersky/sendoff/blob/890c3591714a9ae505ddf1d92d4faedc93e4b2c3/sendoff/sdblock.py#L146

**Comment by pechersky** [comment]
Closed by #20.
